INSERT INTO role(CREATED, UPDATED, DESCRIPTION, NAME) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Developer', 'Developer');
INSERT INTO role(CREATED, UPDATED, DESCRIPTION, NAME) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Project Director', 'Project Director');
INSERT INTO role(CREATED, UPDATED, DESCRIPTION, NAME) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'CTO', 'CTO');
INSERT INTO role(CREATED, UPDATED, DESCRIPTION, NAME) VALUES(CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'CEO', 'CEO');